# SPDX-FileCopyrightText: 2021, 2023, 2024 LogicMonitor, Inc.
#
# SPDX-License-Identifier: LicenseRef-All-rights-reserved

variables:
  AWS_ACC_ID: 560269851512
  AWS_REGION: us-west-2
  AWS_CODEARTIFACT_DOMAIN: dexda
  PRIVATE_PYPI_REPO_SCHEMA: https
  PRIVATE_PYPI_REPO_HOST: ${AWS_CODEARTIFACT_DOMAIN}-${AWS_ACC_ID}.d.codeartifact.${AWS_REGION}.amazonaws.com
  PRIVATE_PYPI_REPO_PATH: /pypi/dexda/
  PRIVATE_PYPI_REPO_URL: ${PRIVATE_PYPI_REPO_SCHEMA}://${PRIVATE_PYPI_REPO_HOST}${PRIVATE_PYPI_REPO_PATH}
  PRIVATE_PYPI_REPO_URL_PIP_SUFFIX: simple/
  PRIVATE_PYPI_REPO_USERNAME: aws
  PRIVATE_CONTAINER_IMG_REPO_REGISTRY: ${AWS_ACC_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
  PRIVATE_CONTAINER_IMG_REPO_USERNAME: AWS
  BUILD_IMG: registry.fedoraproject.org/fedora-minimal:40

stages:
- python-package-build
- python-package-publish
- container-image-build
- container-image-publish

.rules_tagged_only: &rules_tagged_only
- if: '$CI_COMMIT_TAG'
  when: always
- when: never

.script_cd_proj: &script_cd_proj cd "$CI_PROJECT_DIR"
.script_install_build_distro_pkgs: &script_install_build_distro_pkgs dnf5 install -y awscli2 buildah python3-pip skopeo
.script_aws_codeartifact_export_token: &script_aws_codeartifact_export_token export PRIVATE_PYPI_REPO_PASSWORD="$(aws --region="${AWS_REGION}" codeartifact get-authorization-token --domain="${AWS_CODEARTIFACT_DOMAIN}" --domain-owner="${AWS_ACC_ID}" --query=authorizationToken --output=text)"
.script_export_pip_index_url: &script_export_pip_index_url export PIP_INDEX_URL="${PRIVATE_PYPI_REPO_SCHEMA}://${PRIVATE_PYPI_REPO_USERNAME}:${PRIVATE_PYPI_REPO_PASSWORD}@${PRIVATE_PYPI_REPO_HOST}${PRIVATE_PYPI_REPO_PATH}${PRIVATE_PYPI_REPO_URL_PIP_SUFFIX}"
.script_install_build_py_pkgs: &script_install_build_py_pkgs pip3 install .[build]
.script_export_aws_ecr_token: &script_export_aws_ecr_token export PRIVATE_CONTAINER_IMG_REPO_PASSWORD="$(aws --region="${AWS_REGION}" ecr get-login-password)"

job_python-package-build:
  stage: python-package-build
  rules: *rules_tagged_only
  image: ${BUILD_IMG}
  script:
  - *script_cd_proj
  - *script_install_build_distro_pkgs
  - *script_aws_codeartifact_export_token
  - *script_export_pip_index_url
  - *script_install_build_py_pkgs
  - invoke python-package.build
  artifacts:
    paths:
    - build/

job_python-package-publish:
  stage: python-package-publish
  rules: *rules_tagged_only
  image: ${BUILD_IMG}
  script:
  - *script_cd_proj
  - *script_install_build_distro_pkgs
  - *script_aws_codeartifact_export_token
  - *script_export_pip_index_url
  - *script_install_build_py_pkgs
  - invoke python-package.publish

job_container-image-build:
  stage: container-image-build
  rules: *rules_tagged_only
  image: ${BUILD_IMG}
  script:
  - *script_cd_proj
  - *script_install_build_distro_pkgs
  - *script_aws_codeartifact_export_token
  - *script_export_pip_index_url
  - *script_install_build_py_pkgs
  - *script_export_aws_ecr_token
  - invoke container-image.build
  artifacts:
    paths:
    - build/

job_container-image-publish:
  stage: container-image-publish
  rules: *rules_tagged_only
  image: ${BUILD_IMG}
  script:
  - *script_cd_proj
  - *script_install_build_distro_pkgs
  - *script_aws_codeartifact_export_token
  - *script_export_pip_index_url
  - *script_install_build_py_pkgs
  - *script_export_aws_ecr_token
  - invoke container-image.publish
